# Generates assets.rc + web_assets_index.h that embeds every file under
# SOURCE_DIR as RT_RCDATA. The C++ side queries by relative URL path.
#
# Usage:
#   stackr_embed_web_assets(TARGET stackr SOURCE_DIR ${...} OUTPUT_DIR ${...})

function(stackr_embed_web_assets)
    set(options)
    set(oneValueArgs TARGET SOURCE_DIR OUTPUT_DIR)
    set(multiValueArgs)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    file(MAKE_DIRECTORY "${ARG_OUTPUT_DIR}")
    set(rc_path "${ARG_OUTPUT_DIR}/web_assets.rc")
    set(header_path "${ARG_OUTPUT_DIR}/web_assets_index.h")

    if(NOT EXISTS "${ARG_SOURCE_DIR}")
        message(STATUS "[stackr] web/out not found at ${ARG_SOURCE_DIR} — embedding empty index. Run `pnpm build` then re-run CMake.")
        file(WRITE "${rc_path}" "// empty\n")
        file(WRITE "${header_path}"
"#pragma once\n"
"#include <cstddef>\n"
"#include <string_view>\n"
"namespace stackr::web_assets {\n"
"struct Entry { std::string_view path; int resource_id; std::string_view mime; };\n"
"inline constexpr Entry kEntries[] = {};\n"
"inline constexpr size_t kEntryCount = 0;\n"
"}\n")
        target_sources(${ARG_TARGET} PRIVATE "${rc_path}")
        return()
    endif()

    file(GLOB_RECURSE web_files RELATIVE "${ARG_SOURCE_DIR}" "${ARG_SOURCE_DIR}/*")
    list(LENGTH web_files file_count)
    message(STATUS "[stackr] Embedding ${file_count} web asset(s) from ${ARG_SOURCE_DIR}")

    set(rc_content "// Auto-generated by stackr_embed_web_assets. Do not edit.\n#include <windows.h>\n\n")
    set(header_entries "")
    set(rid 1000)

    foreach(rel IN LISTS web_files)
        file(TO_NATIVE_PATH "${ARG_SOURCE_DIR}/${rel}" abs_path)
        # Backslashes for .rc syntax
        string(REPLACE "\\" "\\\\" rc_abs_path "${abs_path}")

        # Determine mime
        string(TOLOWER "${rel}" rel_lower)
        set(mime "application/octet-stream")
        if(rel_lower MATCHES "\\.html?$")
            set(mime "text/html; charset=utf-8")
        elseif(rel_lower MATCHES "\\.css$")
            set(mime "text/css; charset=utf-8")
        elseif(rel_lower MATCHES "\\.m?js$")
            set(mime "application/javascript; charset=utf-8")
        elseif(rel_lower MATCHES "\\.json$")
            set(mime "application/json; charset=utf-8")
        elseif(rel_lower MATCHES "\\.svg$")
            set(mime "image/svg+xml")
        elseif(rel_lower MATCHES "\\.png$")
            set(mime "image/png")
        elseif(rel_lower MATCHES "\\.jpe?g$")
            set(mime "image/jpeg")
        elseif(rel_lower MATCHES "\\.webp$")
            set(mime "image/webp")
        elseif(rel_lower MATCHES "\\.ico$")
            set(mime "image/x-icon")
        elseif(rel_lower MATCHES "\\.woff2$")
            set(mime "font/woff2")
        elseif(rel_lower MATCHES "\\.woff$")
            set(mime "font/woff")
        elseif(rel_lower MATCHES "\\.txt$")
            set(mime "text/plain; charset=utf-8")
        elseif(rel_lower MATCHES "\\.map$")
            set(mime "application/json")
        endif()

        # Normalize URL path to forward slashes
        string(REPLACE "\\" "/" url_path "/${rel}")

        string(APPEND rc_content "${rid} RCDATA \"${rc_abs_path}\"\n")
        string(APPEND header_entries "    { \"${url_path}\", ${rid}, \"${mime}\" },\n")

        math(EXPR rid "${rid} + 1")
    endforeach()

    file(WRITE "${rc_path}" "${rc_content}")
    file(WRITE "${header_path}"
"// Auto-generated by stackr_embed_web_assets. Do not edit.\n"
"#pragma once\n"
"#include <cstddef>\n"
"#include <string_view>\n"
"namespace stackr::web_assets {\n"
"struct Entry { std::string_view path; int resource_id; std::string_view mime; };\n"
"inline constexpr Entry kEntries[] = {\n"
"${header_entries}"
"};\n"
"inline constexpr size_t kEntryCount = sizeof(kEntries) / sizeof(kEntries[0]);\n"
"}\n")

    target_sources(${ARG_TARGET} PRIVATE "${rc_path}")
endfunction()
